# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FmdData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date_observed', models.DateField()),
                ('time_observed', models.TimeField()),
                ('farm_condition', models.TextField()),
                ('bgp_requirements', models.TextField()),
                ('corrective_action', models.TextField()),
                ('hand_delivered_date', models.DateField()),
                ('hand_delivered_time', models.TimeField()),
                ('corrected_date', models.DateField()),
                ('corrected_time', models.TimeField()),
                ('fmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmd.Farm')),
            ],
        ),
    ]
